/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as CloudRouteRouteImport } from './routes/cloud/route'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppTagsRouteImport } from './routes/_app/tags'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AuthSshRouteImport } from './routes/auth/ssh'
import { Route as CloudIndexRouteImport } from './routes/cloud/index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as AppEdgesIndexRouteImport } from './routes/_app/edges/index'
import { Route as AppEdgesEdgeIdRouteImport } from './routes/_app/edges/$edgeId'
import { Route as AppKubernetesIndexRouteImport } from './routes/_app/kubernetes/index'
import { Route as AppMachinesIndexRouteImport } from './routes/_app/machines/index'
import { Route as AppMachinesEndpointIdRouteImport } from './routes/_app/machines/$endpointId'
import { Route as AppNetworksIndexRouteImport } from './routes/_app/networks/index'
import { Route as AppNetworksNetworkIdRouteRouteImport } from './routes/_app/networks/$networkId/route'
import { Route as AppPostureIndexRouteImport } from './routes/_app/posture/index'
import { Route as AppPostureComplianceRouteImport } from './routes/_app/posture/compliance'
import { Route as AppPostureIntegrationsRouteImport } from './routes/_app/posture/integrations'
import { Route as AppRelaysIndexRouteImport } from './routes/_app/relays/index'
import { Route as AppRelaysRelayIdRouteImport } from './routes/_app/relays/$relayId'
import { Route as AppServesIndexRouteImport } from './routes/_app/serves/index'
import { Route as AppServesServeIdRouteImport } from './routes/_app/serves/$serveId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSshSessionsIndexRouteImport } from './routes/_app/ssh-sessions/index'
import { Route as AppTransfersIndexRouteImport } from './routes/_app/transfers/index'
import { Route as AppTunnelsIndexRouteImport } from './routes/_app/tunnels/index'
import { Route as AppTunnelsTunnelIdRouteImport } from './routes/_app/tunnels/$tunnelId'
import { Route as CloudRelaysIndexRouteImport } from './routes/cloud/relays/index'
import { Route as CloudRelaysRelayIdRouteImport } from './routes/cloud/relays/$relayId'
import { Route as AppKubernetesNetworksNetworkIdRouteImport } from './routes/_app/kubernetes/networks/$networkId'
import { Route as AppNetworksNetworkIdIndexRouteImport } from './routes/_app/networks/$networkId/index'
import { Route as AppNetworksNetworkIdAccessRouteImport } from './routes/_app/networks/$networkId/access'
import { Route as AppNetworksNetworkIdEnrollmentRouteImport } from './routes/_app/networks/$networkId/enrollment'
import { Route as AppNetworksNetworkIdMachinesRouteImport } from './routes/_app/networks/$networkId/machines'
import { Route as AppNetworksNetworkIdMapRouteImport } from './routes/_app/networks/$networkId/map'
import { Route as AppNetworksNetworkIdPolicyRouteImport } from './routes/_app/networks/$networkId/policy'
import { Route as AppNetworksNetworkIdRoutesRouteImport } from './routes/_app/networks/$networkId/routes'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRouteRoute = CloudRouteRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSshRoute = AuthSshRouteImport.update({
  id: '/auth/ssh',
  path: '/auth/ssh',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudIndexRoute = CloudIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CloudRouteRoute,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/device/approve',
  path: '/device/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEdgesIndexRoute = AppEdgesIndexRouteImport.update({
  id: '/edges/',
  path: '/edges/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEdgesEdgeIdRoute = AppEdgesEdgeIdRouteImport.update({
  id: '/edges/$edgeId',
  path: '/edges/$edgeId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKubernetesIndexRoute = AppKubernetesIndexRouteImport.update({
  id: '/kubernetes/',
  path: '/kubernetes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMachinesIndexRoute = AppMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMachinesEndpointIdRoute = AppMachinesEndpointIdRouteImport.update({
  id: '/machines/$endpointId',
  path: '/machines/$endpointId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNetworksIndexRoute = AppNetworksIndexRouteImport.update({
  id: '/networks/',
  path: '/networks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNetworksNetworkIdRouteRoute =
  AppNetworksNetworkIdRouteRouteImport.update({
    id: '/networks/$networkId',
    path: '/networks/$networkId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPostureIndexRoute = AppPostureIndexRouteImport.update({
  id: '/posture/',
  path: '/posture/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostureComplianceRoute = AppPostureComplianceRouteImport.update({
  id: '/posture/compliance',
  path: '/posture/compliance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostureIntegrationsRoute = AppPostureIntegrationsRouteImport.update({
  id: '/posture/integrations',
  path: '/posture/integrations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelaysIndexRoute = AppRelaysIndexRouteImport.update({
  id: '/relays/',
  path: '/relays/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelaysRelayIdRoute = AppRelaysRelayIdRouteImport.update({
  id: '/relays/$relayId',
  path: '/relays/$relayId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServesIndexRoute = AppServesIndexRouteImport.update({
  id: '/serves/',
  path: '/serves/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServesServeIdRoute = AppServesServeIdRouteImport.update({
  id: '/serves/$serveId',
  path: '/serves/$serveId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSshSessionsIndexRoute = AppSshSessionsIndexRouteImport.update({
  id: '/ssh-sessions/',
  path: '/ssh-sessions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransfersIndexRoute = AppTransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTunnelsIndexRoute = AppTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTunnelsTunnelIdRoute = AppTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => AppRouteRoute,
} as any)
const CloudRelaysIndexRoute = CloudRelaysIndexRouteImport.update({
  id: '/relays/',
  path: '/relays/',
  getParentRoute: () => CloudRouteRoute,
} as any)
const CloudRelaysRelayIdRoute = CloudRelaysRelayIdRouteImport.update({
  id: '/relays/$relayId',
  path: '/relays/$relayId',
  getParentRoute: () => CloudRouteRoute,
} as any)
const AppKubernetesNetworksNetworkIdRoute =
  AppKubernetesNetworksNetworkIdRouteImport.update({
    id: '/kubernetes/networks/$networkId',
    path: '/kubernetes/networks/$networkId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppNetworksNetworkIdIndexRoute =
  AppNetworksNetworkIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdAccessRoute =
  AppNetworksNetworkIdAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdEnrollmentRoute =
  AppNetworksNetworkIdEnrollmentRouteImport.update({
    id: '/enrollment',
    path: '/enrollment',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdMachinesRoute =
  AppNetworksNetworkIdMachinesRouteImport.update({
    id: '/machines',
    path: '/machines',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdMapRoute = AppNetworksNetworkIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppNetworksNetworkIdRouteRoute,
} as any)
const AppNetworksNetworkIdPolicyRoute =
  AppNetworksNetworkIdPolicyRouteImport.update({
    id: '/policy',
    path: '/policy',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)
const AppNetworksNetworkIdRoutesRoute =
  AppNetworksNetworkIdRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => AppNetworksNetworkIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cloud': typeof CloudRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/access': typeof AppAccessRoute
  '/logs': typeof AppLogsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/organization': typeof AppOrganizationRoute
  '/roles': typeof AppRolesRoute
  '/tags': typeof AppTagsRoute
  '/users': typeof AppUsersRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/auth/ssh': typeof AuthSshRoute
  '/device/approve': typeof DeviceApproveRoute
  '/cloud/': typeof CloudIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/networks/$networkId': typeof AppNetworksNetworkIdRouteRouteWithChildren
  '/edges/$edgeId': typeof AppEdgesEdgeIdRoute
  '/machines/$endpointId': typeof AppMachinesEndpointIdRoute
  '/posture/compliance': typeof AppPostureComplianceRoute
  '/posture/integrations': typeof AppPostureIntegrationsRoute
  '/relays/$relayId': typeof AppRelaysRelayIdRoute
  '/serves/$serveId': typeof AppServesServeIdRoute
  '/tunnels/$tunnelId': typeof AppTunnelsTunnelIdRoute
  '/cloud/relays/$relayId': typeof CloudRelaysRelayIdRoute
  '/edges/': typeof AppEdgesIndexRoute
  '/kubernetes/': typeof AppKubernetesIndexRoute
  '/machines/': typeof AppMachinesIndexRoute
  '/networks/': typeof AppNetworksIndexRoute
  '/posture/': typeof AppPostureIndexRoute
  '/relays/': typeof AppRelaysIndexRoute
  '/serves/': typeof AppServesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/ssh-sessions/': typeof AppSshSessionsIndexRoute
  '/transfers/': typeof AppTransfersIndexRoute
  '/tunnels/': typeof AppTunnelsIndexRoute
  '/cloud/relays/': typeof CloudRelaysIndexRoute
  '/kubernetes/networks/$networkId': typeof AppKubernetesNetworksNetworkIdRoute
  '/networks/$networkId/access': typeof AppNetworksNetworkIdAccessRoute
  '/networks/$networkId/enrollment': typeof AppNetworksNetworkIdEnrollmentRoute
  '/networks/$networkId/machines': typeof AppNetworksNetworkIdMachinesRoute
  '/networks/$networkId/map': typeof AppNetworksNetworkIdMapRoute
  '/networks/$networkId/policy': typeof AppNetworksNetworkIdPolicyRoute
  '/networks/$networkId/routes': typeof AppNetworksNetworkIdRoutesRoute
  '/networks/$networkId/': typeof AppNetworksNetworkIdIndexRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/logs': typeof AppLogsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/organization': typeof AppOrganizationRoute
  '/roles': typeof AppRolesRoute
  '/tags': typeof AppTagsRoute
  '/users': typeof AppUsersRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/auth/ssh': typeof AuthSshRoute
  '/device/approve': typeof DeviceApproveRoute
  '/': typeof AppIndexRoute
  '/cloud': typeof CloudIndexRoute
  '/device': typeof DeviceIndexRoute
  '/edges/$edgeId': typeof AppEdgesEdgeIdRoute
  '/machines/$endpointId': typeof AppMachinesEndpointIdRoute
  '/posture/compliance': typeof AppPostureComplianceRoute
  '/posture/integrations': typeof AppPostureIntegrationsRoute
  '/relays/$relayId': typeof AppRelaysRelayIdRoute
  '/serves/$serveId': typeof AppServesServeIdRoute
  '/tunnels/$tunnelId': typeof AppTunnelsTunnelIdRoute
  '/cloud/relays/$relayId': typeof CloudRelaysRelayIdRoute
  '/edges': typeof AppEdgesIndexRoute
  '/kubernetes': typeof AppKubernetesIndexRoute
  '/machines': typeof AppMachinesIndexRoute
  '/networks': typeof AppNetworksIndexRoute
  '/posture': typeof AppPostureIndexRoute
  '/relays': typeof AppRelaysIndexRoute
  '/serves': typeof AppServesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/ssh-sessions': typeof AppSshSessionsIndexRoute
  '/transfers': typeof AppTransfersIndexRoute
  '/tunnels': typeof AppTunnelsIndexRoute
  '/cloud/relays': typeof CloudRelaysIndexRoute
  '/kubernetes/networks/$networkId': typeof AppKubernetesNetworksNetworkIdRoute
  '/networks/$networkId/access': typeof AppNetworksNetworkIdAccessRoute
  '/networks/$networkId/enrollment': typeof AppNetworksNetworkIdEnrollmentRoute
  '/networks/$networkId/machines': typeof AppNetworksNetworkIdMachinesRoute
  '/networks/$networkId/map': typeof AppNetworksNetworkIdMapRoute
  '/networks/$networkId/policy': typeof AppNetworksNetworkIdPolicyRoute
  '/networks/$networkId/routes': typeof AppNetworksNetworkIdRoutesRoute
  '/networks/$networkId': typeof AppNetworksNetworkIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/cloud': typeof CloudRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/access': typeof AppAccessRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/tags': typeof AppTagsRoute
  '/_app/users': typeof AppUsersRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/auth/ssh': typeof AuthSshRoute
  '/device/approve': typeof DeviceApproveRoute
  '/_app/': typeof AppIndexRoute
  '/cloud/': typeof CloudIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/_app/networks/$networkId': typeof AppNetworksNetworkIdRouteRouteWithChildren
  '/_app/edges/$edgeId': typeof AppEdgesEdgeIdRoute
  '/_app/machines/$endpointId': typeof AppMachinesEndpointIdRoute
  '/_app/posture/compliance': typeof AppPostureComplianceRoute
  '/_app/posture/integrations': typeof AppPostureIntegrationsRoute
  '/_app/relays/$relayId': typeof AppRelaysRelayIdRoute
  '/_app/serves/$serveId': typeof AppServesServeIdRoute
  '/_app/tunnels/$tunnelId': typeof AppTunnelsTunnelIdRoute
  '/cloud/relays/$relayId': typeof CloudRelaysRelayIdRoute
  '/_app/edges/': typeof AppEdgesIndexRoute
  '/_app/kubernetes/': typeof AppKubernetesIndexRoute
  '/_app/machines/': typeof AppMachinesIndexRoute
  '/_app/networks/': typeof AppNetworksIndexRoute
  '/_app/posture/': typeof AppPostureIndexRoute
  '/_app/relays/': typeof AppRelaysIndexRoute
  '/_app/serves/': typeof AppServesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/ssh-sessions/': typeof AppSshSessionsIndexRoute
  '/_app/transfers/': typeof AppTransfersIndexRoute
  '/_app/tunnels/': typeof AppTunnelsIndexRoute
  '/cloud/relays/': typeof CloudRelaysIndexRoute
  '/_app/kubernetes/networks/$networkId': typeof AppKubernetesNetworksNetworkIdRoute
  '/_app/networks/$networkId/access': typeof AppNetworksNetworkIdAccessRoute
  '/_app/networks/$networkId/enrollment': typeof AppNetworksNetworkIdEnrollmentRoute
  '/_app/networks/$networkId/machines': typeof AppNetworksNetworkIdMachinesRoute
  '/_app/networks/$networkId/map': typeof AppNetworksNetworkIdMapRoute
  '/_app/networks/$networkId/policy': typeof AppNetworksNetworkIdPolicyRoute
  '/_app/networks/$networkId/routes': typeof AppNetworksNetworkIdRoutesRoute
  '/_app/networks/$networkId/': typeof AppNetworksNetworkIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cloud'
    | '/consent'
    | '/login'
    | '/settings'
    | '/access'
    | '/logs'
    | '/onboarding'
    | '/organization'
    | '/roles'
    | '/tags'
    | '/users'
    | '/accept-invitation/$invitationId'
    | '/auth/ssh'
    | '/device/approve'
    | '/cloud/'
    | '/device/'
    | '/networks/$networkId'
    | '/edges/$edgeId'
    | '/machines/$endpointId'
    | '/posture/compliance'
    | '/posture/integrations'
    | '/relays/$relayId'
    | '/serves/$serveId'
    | '/tunnels/$tunnelId'
    | '/cloud/relays/$relayId'
    | '/edges/'
    | '/kubernetes/'
    | '/machines/'
    | '/networks/'
    | '/posture/'
    | '/relays/'
    | '/serves/'
    | '/settings/'
    | '/ssh-sessions/'
    | '/transfers/'
    | '/tunnels/'
    | '/cloud/relays/'
    | '/kubernetes/networks/$networkId'
    | '/networks/$networkId/access'
    | '/networks/$networkId/enrollment'
    | '/networks/$networkId/machines'
    | '/networks/$networkId/map'
    | '/networks/$networkId/policy'
    | '/networks/$networkId/routes'
    | '/networks/$networkId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/consent'
    | '/login'
    | '/access'
    | '/logs'
    | '/onboarding'
    | '/organization'
    | '/roles'
    | '/tags'
    | '/users'
    | '/accept-invitation/$invitationId'
    | '/auth/ssh'
    | '/device/approve'
    | '/'
    | '/cloud'
    | '/device'
    | '/edges/$edgeId'
    | '/machines/$endpointId'
    | '/posture/compliance'
    | '/posture/integrations'
    | '/relays/$relayId'
    | '/serves/$serveId'
    | '/tunnels/$tunnelId'
    | '/cloud/relays/$relayId'
    | '/edges'
    | '/kubernetes'
    | '/machines'
    | '/networks'
    | '/posture'
    | '/relays'
    | '/serves'
    | '/settings'
    | '/ssh-sessions'
    | '/transfers'
    | '/tunnels'
    | '/cloud/relays'
    | '/kubernetes/networks/$networkId'
    | '/networks/$networkId/access'
    | '/networks/$networkId/enrollment'
    | '/networks/$networkId/machines'
    | '/networks/$networkId/map'
    | '/networks/$networkId/policy'
    | '/networks/$networkId/routes'
    | '/networks/$networkId'
  id:
    | '__root__'
    | '/_app'
    | '/cloud'
    | '/consent'
    | '/login'
    | '/_app/settings'
    | '/_app/access'
    | '/_app/logs'
    | '/_app/onboarding'
    | '/_app/organization'
    | '/_app/roles'
    | '/_app/tags'
    | '/_app/users'
    | '/accept-invitation/$invitationId'
    | '/auth/ssh'
    | '/device/approve'
    | '/_app/'
    | '/cloud/'
    | '/device/'
    | '/_app/networks/$networkId'
    | '/_app/edges/$edgeId'
    | '/_app/machines/$endpointId'
    | '/_app/posture/compliance'
    | '/_app/posture/integrations'
    | '/_app/relays/$relayId'
    | '/_app/serves/$serveId'
    | '/_app/tunnels/$tunnelId'
    | '/cloud/relays/$relayId'
    | '/_app/edges/'
    | '/_app/kubernetes/'
    | '/_app/machines/'
    | '/_app/networks/'
    | '/_app/posture/'
    | '/_app/relays/'
    | '/_app/serves/'
    | '/_app/settings/'
    | '/_app/ssh-sessions/'
    | '/_app/transfers/'
    | '/_app/tunnels/'
    | '/cloud/relays/'
    | '/_app/kubernetes/networks/$networkId'
    | '/_app/networks/$networkId/access'
    | '/_app/networks/$networkId/enrollment'
    | '/_app/networks/$networkId/machines'
    | '/_app/networks/$networkId/map'
    | '/_app/networks/$networkId/policy'
    | '/_app/networks/$networkId/routes'
    | '/_app/networks/$networkId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CloudRouteRoute: typeof CloudRouteRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AuthSshRoute: typeof AuthSshRoute
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/ssh': {
      id: '/auth/ssh'
      path: '/auth/ssh'
      fullPath: '/auth/ssh'
      preLoaderRoute: typeof AuthSshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/': {
      id: '/cloud/'
      path: '/'
      fullPath: '/cloud/'
      preLoaderRoute: typeof CloudIndexRouteImport
      parentRoute: typeof CloudRouteRoute
    }
    '/device/': {
      id: '/device/'
      path: '/device'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/device/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/edges/': {
      id: '/_app/edges/'
      path: '/edges'
      fullPath: '/edges/'
      preLoaderRoute: typeof AppEdgesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/edges/$edgeId': {
      id: '/_app/edges/$edgeId'
      path: '/edges/$edgeId'
      fullPath: '/edges/$edgeId'
      preLoaderRoute: typeof AppEdgesEdgeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/kubernetes/': {
      id: '/_app/kubernetes/'
      path: '/kubernetes'
      fullPath: '/kubernetes/'
      preLoaderRoute: typeof AppKubernetesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/machines/': {
      id: '/_app/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof AppMachinesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/machines/$endpointId': {
      id: '/_app/machines/$endpointId'
      path: '/machines/$endpointId'
      fullPath: '/machines/$endpointId'
      preLoaderRoute: typeof AppMachinesEndpointIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/networks/': {
      id: '/_app/networks/'
      path: '/networks'
      fullPath: '/networks/'
      preLoaderRoute: typeof AppNetworksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/networks/$networkId': {
      id: '/_app/networks/$networkId'
      path: '/networks/$networkId'
      fullPath: '/networks/$networkId'
      preLoaderRoute: typeof AppNetworksNetworkIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posture/': {
      id: '/_app/posture/'
      path: '/posture'
      fullPath: '/posture/'
      preLoaderRoute: typeof AppPostureIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posture/compliance': {
      id: '/_app/posture/compliance'
      path: '/posture/compliance'
      fullPath: '/posture/compliance'
      preLoaderRoute: typeof AppPostureComplianceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posture/integrations': {
      id: '/_app/posture/integrations'
      path: '/posture/integrations'
      fullPath: '/posture/integrations'
      preLoaderRoute: typeof AppPostureIntegrationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/relays/': {
      id: '/_app/relays/'
      path: '/relays'
      fullPath: '/relays/'
      preLoaderRoute: typeof AppRelaysIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/relays/$relayId': {
      id: '/_app/relays/$relayId'
      path: '/relays/$relayId'
      fullPath: '/relays/$relayId'
      preLoaderRoute: typeof AppRelaysRelayIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/serves/': {
      id: '/_app/serves/'
      path: '/serves'
      fullPath: '/serves/'
      preLoaderRoute: typeof AppServesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/serves/$serveId': {
      id: '/_app/serves/$serveId'
      path: '/serves/$serveId'
      fullPath: '/serves/$serveId'
      preLoaderRoute: typeof AppServesServeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/ssh-sessions/': {
      id: '/_app/ssh-sessions/'
      path: '/ssh-sessions'
      fullPath: '/ssh-sessions/'
      preLoaderRoute: typeof AppSshSessionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transfers/': {
      id: '/_app/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AppTransfersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tunnels/': {
      id: '/_app/tunnels/'
      path: '/tunnels'
      fullPath: '/tunnels/'
      preLoaderRoute: typeof AppTunnelsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tunnels/$tunnelId': {
      id: '/_app/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/tunnels/$tunnelId'
      preLoaderRoute: typeof AppTunnelsTunnelIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/cloud/relays/': {
      id: '/cloud/relays/'
      path: '/relays'
      fullPath: '/cloud/relays/'
      preLoaderRoute: typeof CloudRelaysIndexRouteImport
      parentRoute: typeof CloudRouteRoute
    }
    '/cloud/relays/$relayId': {
      id: '/cloud/relays/$relayId'
      path: '/relays/$relayId'
      fullPath: '/cloud/relays/$relayId'
      preLoaderRoute: typeof CloudRelaysRelayIdRouteImport
      parentRoute: typeof CloudRouteRoute
    }
    '/_app/kubernetes/networks/$networkId': {
      id: '/_app/kubernetes/networks/$networkId'
      path: '/kubernetes/networks/$networkId'
      fullPath: '/kubernetes/networks/$networkId'
      preLoaderRoute: typeof AppKubernetesNetworksNetworkIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/networks/$networkId/': {
      id: '/_app/networks/$networkId/'
      path: '/'
      fullPath: '/networks/$networkId/'
      preLoaderRoute: typeof AppNetworksNetworkIdIndexRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/_app/networks/$networkId/access': {
      id: '/_app/networks/$networkId/access'
      path: '/access'
      fullPath: '/networks/$networkId/access'
      preLoaderRoute: typeof AppNetworksNetworkIdAccessRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/_app/networks/$networkId/enrollment': {
      id: '/_app/networks/$networkId/enrollment'
      path: '/enrollment'
      fullPath: '/networks/$networkId/enrollment'
      preLoaderRoute: typeof AppNetworksNetworkIdEnrollmentRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/_app/networks/$networkId/machines': {
      id: '/_app/networks/$networkId/machines'
      path: '/machines'
      fullPath: '/networks/$networkId/machines'
      preLoaderRoute: typeof AppNetworksNetworkIdMachinesRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/_app/networks/$networkId/map': {
      id: '/_app/networks/$networkId/map'
      path: '/map'
      fullPath: '/networks/$networkId/map'
      preLoaderRoute: typeof AppNetworksNetworkIdMapRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/_app/networks/$networkId/policy': {
      id: '/_app/networks/$networkId/policy'
      path: '/policy'
      fullPath: '/networks/$networkId/policy'
      preLoaderRoute: typeof AppNetworksNetworkIdPolicyRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
    '/_app/networks/$networkId/routes': {
      id: '/_app/networks/$networkId/routes'
      path: '/routes'
      fullPath: '/networks/$networkId/routes'
      preLoaderRoute: typeof AppNetworksNetworkIdRoutesRouteImport
      parentRoute: typeof AppNetworksNetworkIdRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppNetworksNetworkIdRouteRouteChildren {
  AppNetworksNetworkIdAccessRoute: typeof AppNetworksNetworkIdAccessRoute
  AppNetworksNetworkIdEnrollmentRoute: typeof AppNetworksNetworkIdEnrollmentRoute
  AppNetworksNetworkIdMachinesRoute: typeof AppNetworksNetworkIdMachinesRoute
  AppNetworksNetworkIdMapRoute: typeof AppNetworksNetworkIdMapRoute
  AppNetworksNetworkIdPolicyRoute: typeof AppNetworksNetworkIdPolicyRoute
  AppNetworksNetworkIdRoutesRoute: typeof AppNetworksNetworkIdRoutesRoute
  AppNetworksNetworkIdIndexRoute: typeof AppNetworksNetworkIdIndexRoute
}

const AppNetworksNetworkIdRouteRouteChildren: AppNetworksNetworkIdRouteRouteChildren =
  {
    AppNetworksNetworkIdAccessRoute: AppNetworksNetworkIdAccessRoute,
    AppNetworksNetworkIdEnrollmentRoute: AppNetworksNetworkIdEnrollmentRoute,
    AppNetworksNetworkIdMachinesRoute: AppNetworksNetworkIdMachinesRoute,
    AppNetworksNetworkIdMapRoute: AppNetworksNetworkIdMapRoute,
    AppNetworksNetworkIdPolicyRoute: AppNetworksNetworkIdPolicyRoute,
    AppNetworksNetworkIdRoutesRoute: AppNetworksNetworkIdRoutesRoute,
    AppNetworksNetworkIdIndexRoute: AppNetworksNetworkIdIndexRoute,
  }

const AppNetworksNetworkIdRouteRouteWithChildren =
  AppNetworksNetworkIdRouteRoute._addFileChildren(
    AppNetworksNetworkIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppAccessRoute: typeof AppAccessRoute
  AppLogsRoute: typeof AppLogsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppRolesRoute: typeof AppRolesRoute
  AppTagsRoute: typeof AppTagsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNetworksNetworkIdRouteRoute: typeof AppNetworksNetworkIdRouteRouteWithChildren
  AppEdgesEdgeIdRoute: typeof AppEdgesEdgeIdRoute
  AppMachinesEndpointIdRoute: typeof AppMachinesEndpointIdRoute
  AppPostureComplianceRoute: typeof AppPostureComplianceRoute
  AppPostureIntegrationsRoute: typeof AppPostureIntegrationsRoute
  AppRelaysRelayIdRoute: typeof AppRelaysRelayIdRoute
  AppServesServeIdRoute: typeof AppServesServeIdRoute
  AppTunnelsTunnelIdRoute: typeof AppTunnelsTunnelIdRoute
  AppEdgesIndexRoute: typeof AppEdgesIndexRoute
  AppKubernetesIndexRoute: typeof AppKubernetesIndexRoute
  AppMachinesIndexRoute: typeof AppMachinesIndexRoute
  AppNetworksIndexRoute: typeof AppNetworksIndexRoute
  AppPostureIndexRoute: typeof AppPostureIndexRoute
  AppRelaysIndexRoute: typeof AppRelaysIndexRoute
  AppServesIndexRoute: typeof AppServesIndexRoute
  AppSshSessionsIndexRoute: typeof AppSshSessionsIndexRoute
  AppTransfersIndexRoute: typeof AppTransfersIndexRoute
  AppTunnelsIndexRoute: typeof AppTunnelsIndexRoute
  AppKubernetesNetworksNetworkIdRoute: typeof AppKubernetesNetworksNetworkIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppAccessRoute: AppAccessRoute,
  AppLogsRoute: AppLogsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppRolesRoute: AppRolesRoute,
  AppTagsRoute: AppTagsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppNetworksNetworkIdRouteRoute: AppNetworksNetworkIdRouteRouteWithChildren,
  AppEdgesEdgeIdRoute: AppEdgesEdgeIdRoute,
  AppMachinesEndpointIdRoute: AppMachinesEndpointIdRoute,
  AppPostureComplianceRoute: AppPostureComplianceRoute,
  AppPostureIntegrationsRoute: AppPostureIntegrationsRoute,
  AppRelaysRelayIdRoute: AppRelaysRelayIdRoute,
  AppServesServeIdRoute: AppServesServeIdRoute,
  AppTunnelsTunnelIdRoute: AppTunnelsTunnelIdRoute,
  AppEdgesIndexRoute: AppEdgesIndexRoute,
  AppKubernetesIndexRoute: AppKubernetesIndexRoute,
  AppMachinesIndexRoute: AppMachinesIndexRoute,
  AppNetworksIndexRoute: AppNetworksIndexRoute,
  AppPostureIndexRoute: AppPostureIndexRoute,
  AppRelaysIndexRoute: AppRelaysIndexRoute,
  AppServesIndexRoute: AppServesIndexRoute,
  AppSshSessionsIndexRoute: AppSshSessionsIndexRoute,
  AppTransfersIndexRoute: AppTransfersIndexRoute,
  AppTunnelsIndexRoute: AppTunnelsIndexRoute,
  AppKubernetesNetworksNetworkIdRoute: AppKubernetesNetworksNetworkIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface CloudRouteRouteChildren {
  CloudIndexRoute: typeof CloudIndexRoute
  CloudRelaysRelayIdRoute: typeof CloudRelaysRelayIdRoute
  CloudRelaysIndexRoute: typeof CloudRelaysIndexRoute
}

const CloudRouteRouteChildren: CloudRouteRouteChildren = {
  CloudIndexRoute: CloudIndexRoute,
  CloudRelaysRelayIdRoute: CloudRelaysRelayIdRoute,
  CloudRelaysIndexRoute: CloudRelaysIndexRoute,
}

const CloudRouteRouteWithChildren = CloudRouteRoute._addFileChildren(
  CloudRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  CloudRouteRoute: CloudRouteRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AuthSshRoute: AuthSshRoute,
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
